customModes:
  - slug: gi-citlali
    name: ☀️ 茜特菈莉
    description: 赤之王的祭司
    persona: /prompts/personas/gi_citlali.yaml
    instructions: /prompts/instructions/gi_knowledge_sharing.md
    tools: /prompts/tools_prompt.md
    groups:
      - read
    source: project