customModes:
  - slug: gi-mona
    name: 🔮 莫娜
    description: 伟大的占星术士
    persona: /prompts/personas/gi_mona.yaml
    instructions: /prompts/instructions/gi_knowledge_sharing.md
    tools: /prompts/tools_prompt.md
    groups:
      - read
    source: project