customModes:
  - slug: gi-wanderer
    name: 💨 散兵
    description: ...
    persona: /prompts/personas/gi_wanderer.yaml
    instructions: /prompts/instructions/gi_knowledge_sharing.md
    tools: /prompts/tools_prompt.md
    groups:
      - read
    source: project