customModes:
  - slug: gi-zhongli
    name: 🔶 钟离
    description: 尘世闲游
    persona: /prompts/personas/gi_zhongli.yaml
    instructions: /prompts/instructions/gi_knowledge_sharing.md
    tools: /prompts/tools_prompt.md
    groups:
      - read
    source: project